### ISSUE TITLE
Parse test suite from embedded yaml

### ISSUE THREAD

**Issue by jmjrawlings** [jmjrawlings/MiniZinc.Net#12]
Included in the test specs from the official repository there are solutions and expected results.  These are perfect test cases if we can parse the comments properly.

Example:

```
/***
!Test
expected:
- !Result
  solution: !Solution
    a:
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]
    - [0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0]
    - [0, 2, 0, 0, 0, 1, 0, 0, 3, 0, 0]
    - [0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0]
    - [0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0]
    - [0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0]
    - [0, 1, 0, 0, 0, 0, 1, 2, 3, 4, 0]
    - [0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    col_sums: [4, 0, 3, 2, 2, 2, 1, 4, 2]
    row_sums: [2, 2, 3, 2, 2, 1, 5, 1, 2]
***/
```
